### ISSUE TITLE
Missing actions and milestones

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/zap-api#7]
Users have identified several projects that are missing certain actions and milestones. The show.sql query provides all of the actions and milestones, but some are missing in the final API response. 

It seems to only be occurring in instances when there are multiple actions with the exact same action id or multiple milestones with the same milestone id. I think this is an issue with the non-explicit serialization.

Maybe we also need to add GUIDs for each project-milestone record so the app can differentiate between milestones of the same milestone id?

**Examples:**
- 2019R0160 should have three "ZA" actions http://zap-api.herokuapp.com/projects/P2013K0364
- P2015K0272 should have four "Land Use Application Filed" milestones http://zap-api.herokuapp.com/projects/P2015K0272
- P2013K0364 should have two "City Council Review" milestones http://zap-api.herokuapp.com/projects/P2013K0364
- P2007M0372: EAST RIVER REALTY CO. has 17 actions associated to it, some Approved and some Withdrawn. Only 4 show on ZAP Search.
- P2008M0117: EAST RIVER REALTY CO. has 5 actions associated to it, some Approved and some Withdrawn. Only 3 show in ZAP Search.

**Comment by hannahkates** [comment]
This is connected to a front-end calculation/display problem:

There are potential issues with our current assumption that there will only be one of each milestone ID. Example: something funky is going on with 73 Avenue U Rezoning, P2013K0364. The project has two city council review milestones (a63beec4-dad0-e711-8116-1458d04e2fb8) and it seems like the date calculation is being done across those two milestones, yielding a negative number. API data: https://zap-api.planninglabs.nyc/projects/P2013K0364

![image](https://user-images.githubusercontent.com/13967925/67042103-27fc2300-f0f5-11e9-8f84-809d6c5de2e8.png)

**Comment by allthesignals** [comment]
Looking at the response we get from the SQL query, these are the numbers I'm seeing:

- 2019R0160: 2
- P2015K0272: 3
- P2013K0364: 2
- P2007M0372: 17
- P2008M0117: 5

This is before it hits the serialization layer.
